### ISSUE TITLE
Invalid timezone regexp?

### ISSUE THREAD

**Issue by antonlindstrom** [holman/fatigue#1]
Hi,
I am getting the error "invalid regular expression; there's no previous pattern, to which '+' would define cardinality at 1: /+0100/ (RegexpError)" in `post_run'.

Full error output:
    /Library/Ruby/Gems/1.8/gems/fatigue-0.0.2/bin/../lib/fatigue/garmin.rb:56:in `post_run': invalid regular expression; there's no previous pattern, to which '+' would define cardinality at 1: /+0100/ (RegexpError)
    from /Library/Ruby/Gems/1.8/gems/fatigue-0.0.2/bin/../lib/fatigue/garmin.rb:53:in`select'
    from /Library/Ruby/Gems/1.8/gems/fatigue-0.0.2/bin/../lib/fatigue/garmin.rb:53:in `post_run'
    from /Library/Ruby/Gems/1.8/gems/fatigue-0.0.2/bin/../lib/fatigue/garmin.rb:87:in`post_runs'
    from /Library/Ruby/Gems/1.8/gems/fatigue-0.0.2/bin/../lib/fatigue/garmin.rb:86:in `each'
    from /Library/Ruby/Gems/1.8/gems/fatigue-0.0.2/bin/../lib/fatigue/garmin.rb:86:in`post_runs'
    from /Library/Ruby/Gems/1.8/gems/fatigue-0.0.2/bin/fatigue:42
    from /usr/bin/fatigue:19:in `load'
    from /usr/bin/fatigue:19

This occurs when it searches for the timezone and does not seem to match the timezone as +0100 is my timezone.

Thanks!

**Comment by holman** [comment]
Hi Anton,

Thanks for filing this issue- looks like zone just needed to be escaped for the regexp. Good to have someone else around the world find these things. :) I pushed a new version- just `gem install fatigue` again and give it another shot.
